
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import PRTC_verifierContractArtifactJson from '../../target/PRTC_project-PRTC_verifier.json' with { type: 'json' };
export const PRTC_verifierContractArtifact = loadContractArtifact(PRTC_verifierContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PRTC_verifier;
 */
export class PRTC_verifierContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, PRTC_verifierContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, PRTC_verifierContract.artifact, wallet) as Promise<PRTC_verifierContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<PRTC_verifierContract>(PublicKeys.default(), wallet, PRTC_verifierContractArtifact, PRTC_verifierContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<PRTC_verifierContract>(publicKeys, wallet, PRTC_verifierContractArtifact, PRTC_verifierContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PRTC_verifierContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PRTC_verifierContract['methods'][M]>
  ) {
    return new DeployMethod<PRTC_verifierContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PRTC_verifierContractArtifact,
      PRTC_verifierContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PRTC_verifierContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PRTC_verifierContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'verification_status'> {
      return {
        verification_status: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'verification_status'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** get_verification_status(incident_id: struct) */
    get_verification_status: ((incident_id: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_incident(incident_id: struct, max_ticket_lifetime_hours: integer, domain_admin_group_sid: integer, event_ids: array, user_rids: array, group_membership: array, ticket_lifetimes: array, _timestamps: array) */
    verify_incident: ((incident_id: AztecAddressLike, max_ticket_lifetime_hours: (bigint | number), domain_admin_group_sid: (bigint | number), event_ids: (bigint | number)[], user_rids: (bigint | number)[], group_membership: (bigint | number)[], ticket_lifetimes: (bigint | number)[], _timestamps: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
